In [1]:
from google import genai


# ============================================================
# 1. GEMINI API KEY
# ============================================================

GEMINI_API_KEY = "apikey"

client = genai.Client(
    api_key=GEMINI_API_KEY
)


# ============================================================
# 2. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Rules:
- Explain concepts using simple layman terms.
- Student level is Beginner.
- Answer exactly 3 short lines.
- Be precise.
- Avoid unnecessary technical jargon.
- Explain technical terms simply when needed.
"""


# ============================================================
# 3. CONVERSATION MEMORY
# ============================================================

conversation_history = []


# ============================================================
# 4. AI TEACHER FUNCTION
# ============================================================

def ask_teacher(
    question,
    subject="AI & Data Science",
    student_level="Beginner",
    language="English"
):

    user_message = f"""
Subject: {subject}
Student Level: {student_level}
Preferred Language: {language}

Student Question:
{question}
"""

    conversation_history.append({
        "role": "user",
        "content": user_message
    })

    # Build conversation
    conversation_text = ""

    for message in conversation_history:

        conversation_text += (
            message["role"].upper()
            + ":\n"
            + message["content"]
            + "\n\n"
        )

    # ========================================================
    # GEMINI API
    # ========================================================

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=conversation_text,
        config={
            "system_instruction": TEACHER_INSTRUCTIONS,
            "temperature": 0.2,
            "max_output_tokens": 500
        }
    )

    answer = response.text.strip()

    # Save response
    conversation_history.append({
        "role": "assistant",
        "content": answer
    })

    return answer


# ============================================================
# 5. CHAT APPLICATION
# ============================================================

def start_teacher():

    print("=" * 60)
    print("                    AI TEACHER")
    print("=" * 60)

    print("Subject : AI & Data Science")
    print("Level   : Beginner")
    print("Language: English")

    print("\nType 'exit' to stop.")
    print("Type 'clear' to clear conversation memory.")

    print("=" * 60)

    while True:

        question = input("\nStudent: ").strip()

        # Exit
        if question.lower() == "exit":

            print("\nTeacher: Keep learning! 👋")
            break

        # Clear memory
        if question.lower() == "clear":

            conversation_history.clear()

            print("\nTeacher: Conversation memory cleared.")
            continue

        # Empty question
        if not question:

            print("\nTeacher: Please ask a question.")
            continue

        # Ask teacher
        try:

            answer = ask_teacher(
                question=question,
                subject="AI & Data Science",
                student_level="Beginner",
                language="English"
            )

            print("\nTeacher:")
            print(answer)

            print("\n" + "-" * 60)

        except Exception as e:

            print("\nError:")
            print(e)


# ============================================================
# 6. RUN
# ============================================================

if __name__ == "__main__":
    start_teacher()

============================================================
                    AI TEACHER
============================================================
Subject : AI & Data Science
Level   : Beginner
Language: English

Type 'exit' to stop.
Type 'clear' to clear conversation memory.
============================================================

Student:  what is ML

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

Teacher:
Machine Learning (ML) is teaching computers to learn from experience, just like humans do.
Instead of writing rules for everything, you feed the computer data so it can discover patterns on its own.
Once it learns these patterns, it can make smart decisions or predictions on brand-new information.

------------------------------------------------------------

Student:  exit

Teacher: Keep learning! 👋

In [3]:
#!pip install -U google-genai

Requirement already satisfied: google-genai in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (2.22.0)
Collecting google-genai
  Downloading google_genai-2.27.0-py3-none-any.whl.metadata (56 kB)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (4.10.0)
Requirement already satisfied: google-auth<3.0.0,>=2.56.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.56.2)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.12.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (2.13.5)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (16.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.3.0)
Requirement already satisfied: idna>=2.8 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.20)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (49.0.0)
Requirement already satisfied: certifi in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.12.5->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.6.3)
Requirement already satisfied: cffi>=2.0.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (2.23)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.56.0->google-auth[requests]<3.0.0,>=2.56.0->google-genai) (0.6.3)
Downloading google_genai-2.27.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -------------------------- ------------- 0.8/1.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 4.5 MB/s  0:00:00
Installing collected packages: google-genai
  Attempting uninstall: google-genai
    Found existing installation: google-genai 2.22.0
    Uninstalling google-genai-2.22.0:
      Successfully uninstalled google-genai-2.22.0
Successfully installed google-genai-2.27.0

# Stage2 -  input Quries- Generate

In [4]:
###### import pandas as pd
from google import genai


# ============================================================
# 1. GEMINI API KEY
# ============================================================

GEMINI_API_KEY = "Apikey"

client = genai.Client(
    api_key=GEMINI_API_KEY
)


# ============================================================
# 2. FILE CONFIGURATION
# ============================================================

INPUT_CSV = "ai_teacher_20_questions.csv"
OUTPUT_CSV = "ai_teacher_results.csv"


# ============================================================
# 3. LOAD DATASET
# ============================================================

df = pd.read_csv(INPUT_CSV)

print("Dataset loaded")
print(f"Number of questions: {len(df)}")


# ============================================================
# 4. CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Query",
    "Teacher Response"
]

for column in required_columns:

    if column not in df.columns:
        raise ValueError(
            f"Missing required column: {column}"
        )


# ============================================================
# 5. AI TEACHER INSTRUCTIONS
# ============================================================

TEACHER_INSTRUCTIONS = """
You are an expert AI Teacher.

Your job is to teach students, not just provide answers.

Teaching rules:
- Explain the concept using simple layman terms.
- Assume the student is a beginner.
- Answer should be precise.
- Give exactly 3 short lines.
- Avoid unnecessary technical jargon.
- Explain technical terms simply when necessary.

Response format:
Explain the concept simply.
"""


# ============================================================
# 6. GENERATE ANSWER
# ============================================================

def generate_answer(question):

    response = client.models.generate_content(
        model="gemini-3.8-flash",
        contents=question,
        config={
            "system_instruction": TEACHER_INSTRUCTIONS,
            "temperature": 0.2,
            "max_output_tokens": 500
        }
    )

    return response.text.strip()


# ============================================================
# 7. GENERATE ANSWERS FOR ALL QUESTIONS
# ============================================================

generated_answers = []

for index, row in df.iterrows():

    question = row["User Query"]

    print("\n" + "=" * 70)
    print(f"Processing {index + 1}/{len(df)}")
    print(f"Question: {question}")

    try:

        answer = generate_answer(question)

        print("Generated Answer:")
        print(answer)

    except Exception as e:

        answer = f"ERROR: {str(e)}"

        print(answer)

    generated_answers.append(answer)


# ============================================================
# 8. ADD GENERATED ANSWERS
# ============================================================

df["GeneratedAnswer"] = generated_answers


# ============================================================
# 9. SELECT FINAL COLUMNS
# ============================================================

df = df[
    [
        "User Query",
        "Teacher Response",
        "GeneratedAnswer"
    ]
]


# ============================================================
# 10. SAVE RESULT
# ============================================================

df.to_csv(
    OUTPUT_CSV,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 11. DISPLAY RESULT
# ============================================================

print("\n" + "=" * 70)
print("AI TEACHER TEST COMPLETED")
print("=" * 70)
print(df.to_string(index=False))

print("\nResult saved to:")
print(OUTPUT_CSV)

Dataset loaded
Number of questions: 20

======================================================================
Processing 1/20
Question: What is AI?
ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

======================================================================
Processing 2/20
Question: How does AI differ from traditional programming?
Generated Answer:
In traditional programming, humans write strict step-by-step rules for the computer to follow

======================================================================
Processing 3/20
Question: What is Machine Learning?
Generated Answer:
Machine learning is teaching computers to learn from experience instead of following strict, pre-written rules.
Just like a child learns to recognize a dog by seeing many dogs, a computer learns by finding patterns in examples.
Once it understands these patterns, it can make smart decisions or predictions on new information all by itself.

======================================================================
Processing 4/20
Question: What is Deep Learning?
ERROR: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

======================================================================
Processing 5/20
Question: What is the difference between AI, ML, and Deep Learning?
Generated Answer:
**Artificial Intelligence (AI)** is the broad concept of making machines smart enough to mimic human

======================================================================
Processing 6/20
Question: What is training data?
Generated Answer:
Training data is the collection of examples, like pictures or text, that an AI studies to learn.
Think of it like a student's practice workbook filled with questions and correct answers.
By practicing on this data, the AI learns patterns so it can solve new problems on its own.

======================================================================
Processing 7/20
Question: What is a Machine Learning model?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 40.046764509s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '40s'}]}}

======================================================================
Processing 8/20
Question: What is supervised learning?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 39.592990399s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39s'}]}}

======================================================================
Processing 9/20
Question: What is unsupervised learning?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 39.093651836s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39s'}]}}

======================================================================
Processing 10/20
Question: What is reinforcement learning?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 38.630670318s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '38s'}]}}

======================================================================
Processing 11/20
Question: What is an LLM?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 38.206735056s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '38s'}]}}

======================================================================
Processing 12/20
Question: What is Generative AI?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 37.788307355s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '37s'}]}}

======================================================================
Processing 13/20
Question: What is a prompt?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 37.355081528s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '37s'}]}}

======================================================================
Processing 14/20
Question: What is Prompt Engineering?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 36.987077545s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '36s'}]}}

======================================================================
Processing 15/20
Question: What is RAG?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 36.640554374s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '36s'}]}}

======================================================================
Processing 16/20
Question: Why is RAG useful?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 36.045816899s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '36s'}]}}

======================================================================
Processing 17/20
Question: What is a vector database?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 35.593582815s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-3.8-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '35s'}]}}

======================================================================
Processing 18/20
Question: What are embeddings?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 35.162044124s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '35s'}]}}

======================================================================
Processing 19/20
Question: What is an AI Agent?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 34.802837784s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}

======================================================================
Processing 20/20
Question: How can AI be used in education?
ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-3.8-flash\nPlease retry in 34.38003548s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-3.8-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}

======================================================================
AI TEACHER TEST COMPLETED
======================================================================

In [3]:
import pandas as pd

In [ ]:
!pip install -U google-genai pandas

# Stage3 - LLM Evaluation- Answer Quality

In [8]:
# ============================================================
# STAGE 3 - LLM ANSWER QUALITY EVALUATION USING DEEPEVAL
# ============================================================

import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig


# ============================================================
# 1. LOAD DATA
# ============================================================

INPUT_FILE = "ai_teacher_results.csv"

df = pd.read_csv(INPUT_FILE)

print("=" * 70)
print("DATASET LOADED")
print("=" * 70)

print(f"Number of rows: {len(df)}")
print(f"Columns: {df.columns.tolist()}")


# ============================================================
# 2. CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Query",
    "Teacher Response",
    "GeneratedAnswer"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print("\nAll required columns found.")


# ============================================================
# 3. REMOVE EMPTY ROWS
# ============================================================

df = df.dropna(
    subset=[
        "User Query",
        "Teacher Response",
        "GeneratedAnswer"
    ]
).reset_index(drop=True)

print(f"Valid questions for evaluation: {len(df)}")


# ============================================================
# 4. CREATE DEEPEVAL TEST CASES
# ============================================================

test_cases = []

for _, row in df.iterrows():

    test_case = LLMTestCase(
        input=str(row["User Query"]),
        actual_output=str(row["GeneratedAnswer"]),
        expected_output=str(row["Teacher Response"])
    )

    test_cases.append(test_case)


print(f"Test cases created: {len(test_cases)}")


# ============================================================
# 5. ANSWER CORRECTNESS METRIC
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model="gpt-4.1",

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.

    Focus on factual correctness and meaning rather than
    exact wording.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    # IMPORTANT:
    # async_mode must be True or False
    async_mode=False
)


# ============================================================
# 6. ANSWER RELEVANCY METRIC
# ============================================================

relevancy = AnswerRelevancyMetric(
    model="gpt-4.1",

    include_reason=True,

    # IMPORTANT:
    # async_mode must be True or False
    async_mode=False
)


# ============================================================
# 7. HELPFULNESS METRIC
# ============================================================

helpfulness = GEval(
    name="Helpfulness",

    model="gpt-4.1",

    criteria="""
    Evaluate how helpful the generated answer is for a
    beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.

    Give a high score when the answer is:

    - clear
    - beginner-friendly
    - relevant
    - educational
    - concise
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    # IMPORTANT:
    # async_mode must be True or False
    async_mode=False
)


# ============================================================
# 8. RUN DEEPEVAL
# ============================================================

print("\n" + "=" * 70)
print("STARTING DEEPEVAL EVALUATION")
print("=" * 70)

print("\nMetrics being evaluated:")
print("1. Answer Correctness")
print("2. Answer Relevancy")
print("3. Helpfulness")

print("\nPlease wait...\n")


result = evaluate(
    test_cases=test_cases,

    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],

    # IMPORTANT FOR JUPYTER / ANACONDA
    # Run evaluation synchronously
    async_config=AsyncConfig(
        run_async=False
    )
)


# ============================================================
# 9. DISPLAY FINAL RESULT
# ============================================================

print("\n" + "=" * 70)
print("DEEPEVAL EVALUATION COMPLETED")
print("=" * 70)

print(result)

======================================================================
DATASET LOADED
======================================================================
Number of rows: 20
Columns: ['User Query', 'Teacher Response', 'GeneratedAnswer']

All required columns found.
Valid questions for evaluation: 20
Test cases created: 20

======================================================================
STARTING DEEPEVAL EVALUATION
======================================================================

Metrics being evaluated:
1. Answer Correctness
2. Answer Relevancy
3. Helpfulness

Please wait...

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

RetryError: RetryError[<Future at 0x1765e600070 state=finished raised RateLimitError>]

In [4]:
%pip install -U deepeval

Collecting deepeval
  Downloading deepeval-4.2.8-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: aiohttp in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (3.14.3)
Collecting click<8.4.0,>=8.0.0 (from deepeval)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: grpcio<2.0.0,>=1.67.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (1.80.0)
Requirement already satisfied: jinja2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (3.1.6)
Requirement already satisfied: nest_asyncio in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (1.6.0)
Requirement already satisfied: openai in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (3.22.1)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.24.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (1.45.0)
Requirement already satisfied: opentelemetry-sdk<2.0.0,>=1.24.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (1.45.0)
Collecting portalocker (from deepeval)
  Downloading portalocker-4.4.0-py3-none-any.whl.metadata (10 kB)
Collecting posthog<8.0.0,>=7.0.0 (from deepeval)
  Downloading posthog-7.62.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.11.7 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (2.13.5)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (2.15.0)
Collecting pyfiglet (from deepeval)
  Downloading pyfiglet-1.0.4-py3-none-any.whl.metadata (7.4 kB)
Collecting pytest (from deepeval)
  Downloading pytest-9.1.1-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-asyncio (from deepeval)
  Downloading pytest_asyncio-1.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting pytest-repeat (from deepeval)
  Downloading pytest_repeat-0.9.4-py3-none-any.whl.metadata (4.9 kB)
Collecting pytest-rerunfailures (from deepeval)
  Downloading pytest_rerunfailures-16.7-py3-none-any.whl.metadata (33 kB)
Collecting pytest-xdist (from deepeval)
  Downloading pytest_xdist-3.8.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: python-dotenv<2.0.0,>=1.1.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (1.2.2)
Collecting questionary<3.0.0,>=2.0.0 (from deepeval)
  Downloading questionary-2.1.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (2.34.2)
Collecting rich<15.0.0,>=13.6.0 (from deepeval)
  Downloading rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: setuptools in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (80.10.2)
Collecting tabulate<0.10.0,>=0.9.0 (from deepeval)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: tenacity<=10.0.0,>=8.0.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (9.1.4)
Requirement already satisfied: tqdm<5.0.0,>=4.66.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (4.67.3)
Requirement already satisfied: typer<1.0.0,>=0.9 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (0.25.1)
Requirement already satisfied: wheel in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from deepeval) (0.46.3)
Requirement already satisfied: colorama in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from click<8.4.0,>=8.0.0->deepeval) (0.4.6)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from grpcio<2.0.0,>=1.67.1->deepeval) (4.15.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.66b0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from opentelemetry-sdk<2.0.0,>=1.24.0->deepeval) (0.66b0)
Requirement already satisfied: backoff>=1.10.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from posthog<8.0.0,>=7.0.0->deepeval) (2.2.1)
Requirement already satisfied: distro>=1.5.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from posthog<8.0.0,>=7.0.0->deepeval) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pydantic<3.0.0,>=2.11.7->deepeval) (0.4.2)
Requirement already satisfied: prompt_toolkit<4.0,>=2.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from questionary<3.0.0,>=2.0.0->deepeval) (3.0.52)
Requirement already satisfied: wcwidth in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from prompt_toolkit<4.0,>=2.0->questionary<3.0.0,>=2.0.0->deepeval) (0.2.14)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.31.0->deepeval) (2026.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from rich<15.0.0,>=13.6.0->deepeval) (2.19.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.9->deepeval) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.9->deepeval) (0.0.4)
Requirement already satisfied: mdurl~=0.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.6.0->deepeval) (0.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from aiohttp->deepeval) (1.25.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from jinja2->deepeval) (3.0.2)
Requirement already satisfied: anyio<5,>=4.10.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from openai->deepeval) (4.10.0)
Requirement already satisfied: httpx2<3,>=2.12.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from openai->deepeval) (2.13.1)
Requirement already satisfied: jiter<1,>=0.16.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from openai->deepeval) (0.17.0)
Requirement already satisfied: sniffio in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from openai->deepeval) (1.3.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from anyio<5,>=4.10.0->openai->deepeval) (1.3.0)
Requirement already satisfied: httpcore2==2.13.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpx2<3,>=2.12.0->openai->deepeval) (2.13.1)
Requirement already satisfied: truststore>=0.10 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpx2<3,>=2.12.0->openai->deepeval) (0.10.4)
Requirement already satisfied: h11>=0.16 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.12.0->openai->deepeval) (0.16.0)
Collecting iniconfig>=1.0.1 (from pytest->deepeval)
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: packaging>=22 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pytest->deepeval) (25.0)
Collecting pluggy<2,>=1.5 (from pytest->deepeval)
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: tomli>=1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from pytest->deepeval) (2.4.0)
Collecting backports-asyncio-runner<2,>=1.1 (from pytest-asyncio->deepeval)
  Downloading backports_asyncio_runner-1.2.0-py3-none-any.whl.metadata (7.5 kB)
Collecting execnet>=2.1 (from pytest-xdist->deepeval)
  Downloading execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Downloading deepeval-4.2.8-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------- ------------------ 0.8/1.5 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.5 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 2.5 MB/s  0:00:00
Downloading click-8.3.3-py3-none-any.whl (110 kB)
Downloading posthog-7.62.0-py3-none-any.whl (818 kB)
   ---------------------------------------- 0.0/818.8 kB ? eta -:--:--
   ------------------------- -------------- 524.3/818.8 kB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 818.8/818.8 kB 3.3 MB/s  0:00:00
Downloading questionary-2.1.1-py3-none-any.whl (36 kB)
Downloading rich-14.3.4-py3-none-any.whl (310 kB)
Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Downloading portalocker-4.4.0-py3-none-any.whl (129 kB)
Downloading pyfiglet-1.0.4-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 4.2 MB/s eta 0:00:01
   ----------------------------- ---------- 1.3/1.8 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.3 MB/s  0:00:00
Downloading pytest-9.1.1-py3-none-any.whl (386 kB)
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Downloading pytest_asyncio-1.4.0-py3-none-any.whl (16 kB)
Downloading backports_asyncio_runner-1.2.0-py3-none-any.whl (12 kB)
Downloading pytest_repeat-0.9.4-py3-none-any.whl (4.2 kB)
Downloading pytest_rerunfailures-16.7-py3-none-any.whl (23 kB)
Downloading pytest_xdist-3.8.0-py3-none-any.whl (46 kB)
Downloading execnet-2.1.2-py3-none-any.whl (40 kB)
Installing collected packages: tabulate, pyfiglet, portalocker, pluggy, iniconfig, execnet, click, backports-asyncio-runner, rich, questionary, pytest, posthog, pytest-xdist, pytest-rerunfailures, pytest-repeat, pytest-asyncio, deepeval

   -- -------------------------------------  1/17 [pyfiglet]
   -- -------------------------------------  1/17 [pyfiglet]
   -- -------------------------------------  1/17 [pyfiglet]
   -- -------------------------------------  1/17 [pyfiglet]
   --------- ------------------------------  4/17 [iniconfig]
   ----------- ----------------------------  5/17 [execnet]
  Attempting uninstall: click
   ----------- ----------------------------  5/17 [execnet]
    Found existing installation: click 8.4.2
   ----------- ----------------------------  5/17 [execnet]
    Uninstalling click-8.4.2:
   ----------- ----------------------------  5/17 [execnet]
      Successfully uninstalled click-8.4.2
   ----------- ----------------------------  5/17 [execnet]
   -------------- -------------------------  6/17 [click]
  Attempting uninstall: rich
   -------------- -------------------------  6/17 [click]
    Found existing installation: rich 15.0.0
   -------------- -------------------------  6/17 [click]
    Uninstalling rich-15.0.0:
   -------------- -------------------------  6/17 [click]
      Successfully uninstalled rich-15.0.0
   -------------- -------------------------  6/17 [click]
   ------------------ ---------------------  8/17 [rich]
   ------------------ ---------------------  8/17 [rich]
   ------------------ ---------------------  8/17 [rich]
   ------------------ ---------------------  8/17 [rich]
   ------------------ ---------------------  8/17 [rich]
   ----------------------- ---------------- 10/17 [pytest]
   ----------------------- ---------------- 10/17 [pytest]
   ----------------------- ---------------- 10/17 [pytest]
   ----------------------- ---------------- 10/17 [pytest]
  Attempting uninstall: posthog
   ----------------------- ---------------- 10/17 [pytest]
    Found existing installation: posthog 3.25.0
   ----------------------- ---------------- 10/17 [pytest]
    Uninstalling posthog-3.25.0:
   ----------------------- ---------------- 10/17 [pytest]
   ------------------------- -------------- 11/17 [posthog]
      Successfully uninstalled posthog-3.25.0
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ------------------------- -------------- 11/17 [posthog]
   ---------------------------- ----------- 12/17 [pytest-xdist]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ------------------------------------- -- 16/17 [deepeval]
   ---------------------------------------- 17/17 [deepeval]

Successfully installed backports-asyncio-runner-1.2.0 click-8.3.3 deepeval-4.2.8 execnet-2.1.2 iniconfig-2.3.0 pluggy-1.6.0 portalocker-4.4.0 posthog-7.62.0 pyfiglet-1.0.4 pytest-9.1.1 pytest-asyncio-1.4.0 pytest-repeat-0.9.4 pytest-rerunfailures-16.7 pytest-xdist-3.8.0 questionary-2.1.1 rich-14.3.4 tabulate-0.9.0
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
huggingface-hub 1.21.0 requires click>=8.4.0, but you have click 8.3.3 which is incompatible.

In [6]:
dir(result)

NameError: name 'result' is not defined

In [7]:
import deepeval

print("DeepEval installed successfully")
print("Version:", deepeval.__version__)

DeepEval installed successfully
Version: 4.2.8

In [8]:
import os

if os.getenv("OPENAI_API_KEY"):
    print("OPENAI_API_KEY is configured")
else:
    print("OPENAI_API_KEY is NOT configured")

OPENAI_API_KEY is configured

In [9]:
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig


# ============================================================
# 1. LOAD DATA
# ============================================================

df = pd.read_csv("ai_teacher_results.csv")

print("=" * 70)
print("DATASET LOADED")
print("=" * 70)

print("Number of questions:", len(df))
print("Columns:", df.columns.tolist())


# ============================================================
# 2. CHECK COLUMNS
# ============================================================

required_columns = [
    "User Query",
    "Teacher Response",
    "GeneratedAnswer"
]

for column in required_columns:
    if column not in df.columns:
        raise ValueError(
            f"Missing required column: {column}"
        )

print("\nAll required columns found.")


# ============================================================
# 3. CREATE TEST CASES
# ============================================================

test_cases = []

for _, row in df.iterrows():

    test_case = LLMTestCase(
        input=str(row["User Query"]),
        actual_output=str(row["GeneratedAnswer"]),
        expected_output=str(row["Teacher Response"])
    )

    test_cases.append(test_case)

print("Test cases created:", len(test_cases))


# ============================================================
# 4. ANSWER CORRECTNESS
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model="gpt-4.1",

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts
    are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.

    Focus on factual correctness and meaning rather than
    exact wording.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 5. ANSWER RELEVANCY
# ============================================================

relevancy = AnswerRelevancyMetric(
    model="gpt-4.1",

    include_reason=True,

    async_mode=False
)


# ============================================================
# 6. HELPFULNESS
# ============================================================

helpfulness = GEval(
    name="Helpfulness",

    model="gpt-4.1",

    criteria="""
    Evaluate how helpful the generated answer is for a
    beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.

    Give a high score when the answer is:
    - clear
    - beginner-friendly
    - relevant
    - educational
    - concise
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 7. RUN DEEPEVAL
# ============================================================

print("\n" + "=" * 70)
print("STARTING DEEPEVAL")
print("=" * 70)

print("\nEvaluating:")
print("1. Answer Correctness")
print("2. Answer Relevancy")
print("3. Helpfulness")

print("\nPlease wait...\n")


result = evaluate(
    test_cases=test_cases,

    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],

    async_config=AsyncConfig(
        run_async=False
    )
)


# ============================================================
# 8. COMPLETED
# ============================================================

print("\n" + "=" * 70)
print("DEEPEVAL COMPLETED")
print("=" * 70)

print("Result type:")
print(type(result))

print("\nAvailable result attributes:")
print(dir(result))

======================================================================
DATASET LOADED
======================================================================
Number of questions: 20
Columns: ['User Query', 'Teacher Response', 'GeneratedAnswer']

All required columns found.
Test cases created: 20

======================================================================
STARTING DEEPEVAL
======================================================================

Evaluating:
1. Answer Correctness
2. Answer Relevancy
3. Helpfulness

Please wait...

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

RetryError: RetryError[<Future at 0x28f5a953340 state=finished raised RateLimitError>]

In [10]:
result.test_results

NameError: name 'result' is not defined

In [13]:

for i, test_result in enumerate(result.test_results):

    metrics_data = test_result.metrics_data

    df.loc[i, "AnswerCorrectness"] = metrics_data[0].score
    df.loc[i, "AnswerRelevancy"] = metrics_data[1].score
    df.loc[i, "Helpfulness"] = metrics_data[2].score


# ============================================================
# 3. CALCULATE OVERALL ANSWER QUALITY
# ============================================================

df["AnswerQuality"] = (
    df["AnswerCorrectness"]
    + df["AnswerRelevancy"]
    + df["Helpfulness"]
) / 3


# ============================================================
# 4. ROUND SCORES
# ============================================================

metric_columns = [
    "AnswerCorrectness",
    "AnswerRelevancy",
    "Helpfulness",
    "AnswerQuality"
]

df[metric_columns] = df[metric_columns].round(3)


# ============================================================
# 5. AVERAGES
# ============================================================

average_correctness = df["AnswerCorrectness"].mean()
average_relevancy = df["AnswerRelevancy"].mean()
average_helpfulness = df["Helpfulness"].mean()
average_quality = df["AnswerQuality"].mean()


# ============================================================
# 6. QUESTION-WISE RESULTS
# ============================================================

print("\n")
print("=" * 120)
print("                         AI TEACHER ANSWER QUALITY")
print("=" * 120)

display_df = df[
    [
        "User Query",
        "AnswerCorrectness",
        "AnswerRelevancy",
        "Helpfulness",
        "AnswerQuality"
    ]
]


# ============================================================
# 8. SAVE FINAL RESULT
# ============================================================

df.to_csv(
    "ai_teacher_evaluation.csv",
    index=False,
    encoding="utf-8-sig"
)

NameError: name 'result' is not defined

In [14]:
# ============================================================
# DEEPEVAL - RUN EVALUATION AND SAVE SCORES
# ============================================================

import os
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig


# ============================================================
# 1. CHECK OPENAI API KEY
# ============================================================

if not os.getenv("OPENAI_API_KEY"):
    raise ValueError(
        "OPENAI_API_KEY is not configured."
    )

print("OpenAI API key detected.")


# ============================================================
# 2. LOAD CSV
# ============================================================

df = pd.read_csv("ai_teacher_results.csv")

print("Dataset loaded.")
print("Questions:", len(df))


# ============================================================
# 3. CHECK COLUMNS
# ============================================================

required_columns = [
    "User Query",
    "Teacher Response",
    "GeneratedAnswer"
]

missing = [
    col for col in required_columns
    if col not in df.columns
]

if missing:
    raise ValueError(
        f"Missing columns: {missing}"
    )


# ============================================================
# 4. CREATE TEST CASES
# ============================================================

test_cases = []

for _, row in df.iterrows():

    test_cases.append(
        LLMTestCase(
            input=str(row["User Query"]),
            actual_output=str(row["GeneratedAnswer"]),
            expected_output=str(row["Teacher Response"])
        )
    )

print("Test cases created:", len(test_cases))


# ============================================================
# 5. CORRECTNESS METRIC
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model="gpt-4.1",

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts
    are correct.

    Penalize incorrect facts, contradictory information,
    and missing important information.

    Minor wording differences should not reduce the score.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 6. RELEVANCY METRIC
# ============================================================

relevancy = AnswerRelevancyMetric(
    model="gpt-4.1",
    include_reason=True,
    async_mode=False
)


# ============================================================
# 7. HELPFULNESS METRIC
# ============================================================

helpfulness = GEval(
    name="Helpfulness",

    model="gpt-4.1",

    criteria="""
    Evaluate how helpful the generated answer is for a
    beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.

    Give a high score when the answer is clear,
    beginner-friendly, relevant, educational,
    and concise.
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=False
)


# ============================================================
# 8. RUN EVALUATION
# ============================================================

print("\n" + "=" * 70)
print("STARTING DEEPEVAL")
print("=" * 70)

print("Evaluating", len(test_cases), "questions...")
print("Please wait...\n")


# THIS LINE MUST RUN SUCCESSFULLY
result = evaluate(
    test_cases=test_cases,
    metrics=[
        correctness,
        relevancy,
        helpfulness
    ],
    async_config=AsyncConfig(
        run_async=False
    )
)


# ============================================================
# 9. RESULT CREATED
# ============================================================

print("\nEvaluation completed successfully.")

print("Result object:")
print(type(result))


# ============================================================
# 10. EXTRACT SCORES
# ============================================================

df["AnswerCorrectness"] = None
df["AnswerRelevancy"] = None
df["Helpfulness"] = None


for i, test_result in enumerate(result.test_results):

    for metric in test_result.metrics_data:

        metric_name = metric.name
        metric_score = metric.score

        print(
            f"Question {i + 1}: "
            f"{metric_name} = {metric_score}"
        )

        if metric_name == "Answer Correctness":
            df.loc[i, "AnswerCorrectness"] = metric_score

        elif metric_name == "Answer Relevancy":
            df.loc[i, "AnswerRelevancy"] = metric_score

        elif metric_name == "Helpfulness":
            df.loc[i, "Helpfulness"] = metric_score


# ============================================================
# 11. CONVERT SCORES TO NUMERIC
# ============================================================

score_columns = [
    "AnswerCorrectness",
    "AnswerRelevancy",
    "Helpfulness"
]

for column in score_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )


# ============================================================
# 12. OVERALL SCORE
# ============================================================

df["OverallScore"] = df[
    score_columns
].mean(axis=1)


# ============================================================
# 13. SAVE FINAL CSV
# ============================================================

OUTPUT_FILE = "ai_teacher_deepeval_results.csv"

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 14. DISPLAY RESULTS
# ============================================================

print("\n" + "=" * 70)
print("FINAL RESULTS")
print("=" * 70)

display(
    df[
        [
            "User Query",
            "Teacher Response",
            "GeneratedAnswer",
            "AnswerCorrectness",
            "AnswerRelevancy",
            "Helpfulness",
            "OverallScore"
        ]
    ]
)


# ============================================================
# 15. AVERAGE SCORES
# ============================================================

print("\n" + "=" * 70)
print("AVERAGE SCORES")
print("=" * 70)

print(
    "Answer Correctness:",
    round(df["AnswerCorrectness"].mean(), 3)
)

print(
    "Answer Relevancy:",
    round(df["AnswerRelevancy"].mean(), 3)
)

print(
    "Helpfulness:",
    round(df["Helpfulness"].mean(), 3)
)

print(
    "Overall Score:",
    round(df["OverallScore"].mean(), 3)
)


print("\nFinal file saved as:")
print(OUTPUT_FILE)

OpenAI API key detected.
Dataset loaded.
Questions: 20
Test cases created: 20

======================================================================
STARTING DEEPEVAL
======================================================================
Evaluating 20 questions...
Please wait...

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

RetryError: RetryError[<Future at 0x2743cf1db10 state=finished raised RateLimitError>]

In [15]:
# ============================================================
# STAGE 3 - DEEPEVAL EVALUATION
# ONE QUESTION AT A TIME
# ============================================================

import os
import time
import pandas as pd

from deepeval import evaluate
from deepeval.metrics import AnswerRelevancyMetric, GEval
from deepeval.test_case import LLMTestCase, SingleTurnParams
from deepeval.evaluate import AsyncConfig


# ============================================================
# 1. CHECK OPENAI API KEY
# ============================================================

if not os.getenv("OPENAI_API_KEY"):
    raise ValueError(
        "OPENAI_API_KEY is not configured."
    )

print("OpenAI API key detected.")


# ============================================================
# 2. LOAD DATA
# ============================================================

INPUT_FILE = "ai_teacher_results.csv"
OUTPUT_FILE = "ai_teacher_deepeval_results.csv"

df = pd.read_csv(INPUT_FILE)

print("=" * 70)
print("DATASET LOADED")
print("=" * 70)

print("Total questions:", len(df))


# ============================================================
# 3. CHECK REQUIRED COLUMNS
# ============================================================

required_columns = [
    "User Query",
    "Teacher Response",
    "GeneratedAnswer"
]

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing columns: {missing_columns}"
    )


# ============================================================
# 4. CREATE RESULT COLUMNS
# ============================================================

df["AnswerCorrectness"] = None
df["AnswerRelevancy"] = None
df["Helpfulness"] = None
df["OverallScore"] = None


# ============================================================
# 5. CREATE METRICS
# ============================================================

correctness = GEval(
    name="Answer Correctness",

    model="gpt-4.1",

    criteria="""
    Evaluate whether the generated answer is factually correct
    compared with the expected teacher answer.

    Give a high score when the important meaning and facts
    are correct.

    Penalize:
    - incorrect facts
    - contradictory information
    - missing important information

    Minor wording differences should not reduce the score.
    """,

    evaluation_params=[
        SingleTurnParams.ACTUAL_OUTPUT,
        SingleTurnParams.EXPECTED_OUTPUT
    ],

    async_mode=False
)


relevancy = AnswerRelevancyMetric(
    model="gpt-4.1",

    include_reason=False,

    async_mode=False
)


helpfulness = GEval(
    name="Helpfulness",

    model="gpt-4.1",

    criteria="""
    Evaluate how helpful the generated answer is for a
    beginner student.

    A helpful answer should:

    1. Directly answer the student's question.
    2. Be easy to understand.
    3. Provide enough explanation.
    4. Avoid unnecessary information.
    5. Help the student understand the concept.

    Give a high score when the answer is:
    - clear
    - beginner-friendly
    - relevant
    - educational
    - concise
    """,

    evaluation_params=[
        SingleTurnParams.INPUT,
        SingleTurnParams.ACTUAL_OUTPUT
    ],

    async_mode=False
)


metrics = [
    correctness,
    relevancy,
    helpfulness
]


# ============================================================
# 6. EVALUATE ONE QUESTION AT A TIME
# ============================================================

print("\n" + "=" * 70)
print("STARTING DEEPEVAL")
print("=" * 70)


for i, row in df.iterrows():

    print("\n" + "-" * 70)
    print(f"Processing question {i + 1}/{len(df)}")
    print(f"Question: {row['User Query']}")


    # --------------------------------------------------------
    # CREATE SINGLE TEST CASE
    # --------------------------------------------------------

    test_case = LLMTestCase(
        input=str(row["User Query"]),
        actual_output=str(row["GeneratedAnswer"]),
        expected_output=str(row["Teacher Response"])
    )


    # --------------------------------------------------------
    # RETRY CONTROL
    # --------------------------------------------------------

    max_retries = 3
    evaluation_success = False


    for attempt in range(max_retries):

        try:

            print(
                f"Evaluation attempt "
                f"{attempt + 1}/{max_retries}"
            )


            # ------------------------------------------------
            # RUN DEEPEVAL
            # ------------------------------------------------

            result = evaluate(
                test_cases=[test_case],

                metrics=metrics,

                async_config=AsyncConfig(
                    run_async=False
                )
            )


            # ------------------------------------------------
            # EXTRACT RESULT
            # ------------------------------------------------

            test_result = result.test_results[0]

            for metric in test_result.metrics_data:

                metric_name = metric.name
                metric_score = metric.score


                if metric_name == "Answer Correctness":

                    df.loc[
                        i,
                        "AnswerCorrectness"
                    ] = metric_score


                elif metric_name == "Answer Relevancy":

                    df.loc[
                        i,
                        "AnswerRelevancy"
                    ] = metric_score


                elif metric_name == "Helpfulness":

                    df.loc[
                        i,
                        "Helpfulness"
                    ] = metric_score


            # ------------------------------------------------
            # CALCULATE OVERALL SCORE
            # ------------------------------------------------

            scores = [
                df.loc[i, "AnswerCorrectness"],
                df.loc[i, "AnswerRelevancy"],
                df.loc[i, "Helpfulness"]
            ]

            valid_scores = [
                float(score)
                for score in scores
                if pd.notna(score)
            ]

            if valid_scores:

                df.loc[
                    i,
                    "OverallScore"
                ] = sum(valid_scores) / len(valid_scores)


            evaluation_success = True


            print("\nScores:")

            print(
                "Answer Correctness:",
                df.loc[i, "AnswerCorrectness"]
            )

            print(
                "Answer Relevancy:",
                df.loc[i, "AnswerRelevancy"]
            )

            print(
                "Helpfulness:",
                df.loc[i, "Helpfulness"]
            )

            print(
                "Overall Score:",
                df.loc[i, "OverallScore"]
            )


            break


        except Exception as e:

            print(
                f"\nAttempt {attempt + 1} failed:"
            )

            print(str(e))


            if attempt < max_retries - 1:

                wait_time = 10 * (attempt + 1)

                print(
                    f"Waiting {wait_time} seconds "
                    "before retry..."
                )

                time.sleep(wait_time)


            else:

                print(
                    "Maximum retries reached."
                )

                print(
                    "This question will be skipped."
                )


    # --------------------------------------------------------
    # SAVE AFTER EVERY QUESTION
    # --------------------------------------------------------

    df.to_csv(
        OUTPUT_FILE,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"\nProgress saved: "
        f"{i + 1}/{len(df)}"
    )


    # --------------------------------------------------------
    # WAIT BEFORE NEXT QUESTION
    # --------------------------------------------------------

    if evaluation_success:

        print(
            "Waiting before next question..."
        )

        time.sleep(5)


# ============================================================
# 7. FINAL SAVE
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 8. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("DEEPEVAL COMPLETED")
print("=" * 70)


print(
    "Average Answer Correctness:",
    round(
        pd.to_numeric(
            df["AnswerCorrectness"],
            errors="coerce"
        ).mean(),
        3
    )
)


print(
    "Average Answer Relevancy:",
    round(
        pd.to_numeric(
            df["AnswerRelevancy"],
            errors="coerce"
        ).mean(),
        3
    )
)


print(
    "Average Helpfulness:",
    round(
        pd.to_numeric(
            df["Helpfulness"],
            errors="coerce"
        ).mean(),
        3
    )
)


print(
    "Overall Average Score:",
    round(
        pd.to_numeric(
            df["OverallScore"],
            errors="coerce"
        ).mean(),
        3
    )
)


print("\nFinal file:")
print(OUTPUT_FILE)


# ============================================================
# 9. DISPLAY RESULTS
# ============================================================

display(
    df[
        [
            "User Query",
            "Teacher Response",
            "GeneratedAnswer",
            "AnswerCorrectness",
            "AnswerRelevancy",
            "Helpfulness",
            "OverallScore"
        ]
    ]
)

OpenAI API key detected.
======================================================================
DATASET LOADED
======================================================================
Total questions: 20

======================================================================
STARTING DEEPEVAL
======================================================================

----------------------------------------------------------------------
Processing question 1/20
Question: What is AI?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743cfe4a30 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743d07c4c0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1ce590 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 1/20

----------------------------------------------------------------------
Processing question 2/20
Question: How does AI differ from traditional programming?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e1dc3a0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1ed7b0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1ef310 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 2/20

----------------------------------------------------------------------
Processing question 3/20
Question: What is Machine Learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e1dc700 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1cffd0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1b3640 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 3/20

----------------------------------------------------------------------
Processing question 4/20
Question: What is Deep Learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e208580 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e20a980 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e22b7c0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 4/20

----------------------------------------------------------------------
Processing question 5/20
Question: What is the difference between AI, ML, and Deep Learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e21b6d0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1c5ba0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1b27a0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 5/20

----------------------------------------------------------------------
Processing question 6/20
Question: What is training data?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e1d5600 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e238610 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e24beb0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 6/20

----------------------------------------------------------------------
Processing question 7/20
Question: What is a Machine Learning model?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e23b310 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1cc970 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743cfe7b80 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 7/20

----------------------------------------------------------------------
Processing question 8/20
Question: What is supervised learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e21bac0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e271a50 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e255750 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 8/20

----------------------------------------------------------------------
Processing question 9/20
Question: What is unsupervised learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e21aad0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e20a290 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1cf9a0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 9/20

----------------------------------------------------------------------
Processing question 10/20
Question: What is reinforcement learning?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e1de980 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e292980 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e2a2da0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 10/20

----------------------------------------------------------------------
Processing question 11/20
Question: What is an LLM?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e2a1f90 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e291e70 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1dddb0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 11/20

----------------------------------------------------------------------
Processing question 12/20
Question: What is Generative AI?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743ceea6e0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1d5900 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e2d00d0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 12/20

----------------------------------------------------------------------
Processing question 13/20
Question: What is a prompt?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743cf58670 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e22b130 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e20b790 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 13/20

----------------------------------------------------------------------
Processing question 14/20
Question: What is Prompt Engineering?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e255000 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e2a1ff0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e2a3c40 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 14/20

----------------------------------------------------------------------
Processing question 15/20
Question: What is RAG?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e2a0520 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1c5f90 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e209990 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 15/20

----------------------------------------------------------------------
Processing question 16/20
Question: Why is RAG useful?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e1cfe20 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e2d37c0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e1ce770 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 16/20

----------------------------------------------------------------------
Processing question 17/20
Question: What is a vector database?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e2b78e0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1cce80 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743d09fcd0 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 17/20

----------------------------------------------------------------------
Processing question 18/20
Question: What are embeddings?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743cf38a60 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743cf1cc70 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743cee9210 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 18/20

----------------------------------------------------------------------
Processing question 19/20
Question: What is an AI Agent?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743d0aceb0 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743e1cf010 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743e2b7e50 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 19/20

----------------------------------------------------------------------
Processing question 20/20
Question: How can AI be used in education?
Evaluation attempt 1/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 1 failed:
RetryError[<Future at 0x2743e2b4e20 state=finished raised RateLimitError>]
Waiting 10 seconds before retry...
Evaluation attempt 2/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 2 failed:
RetryError[<Future at 0x2743cf388e0 state=finished raised RateLimitError>]
Waiting 20 seconds before retry...
Evaluation attempt 3/3

✨ You're running DeepEval's latest Answer Correctness [GEval] Metric! (using gpt-4.1, strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using gpt-4.1, strict=False, async_mode=False)...

✨ You're running DeepEval's latest Helpfulness [GEval] Metric! (using gpt-4.1, strict=False, async_mode=False)...

Output()

Attempt 3 failed:
RetryError[<Future at 0x2743d09fe80 state=finished raised RateLimitError>]
Maximum retries reached.
This question will be skipped.

Progress saved: 20/20

======================================================================
DEEPEVAL COMPLETED
======================================================================
Average Answer Correctness: nan
Average Answer Relevancy: nan
Average Helpfulness: nan
Overall Average Score: nan

Final file:
ai_teacher_deepeval_results.csv

,User Query,Teacher Response,GeneratedAnswer,AnswerCorrectness,AnswerRelevancy,Helpfulness,OverallScore
0,What is AI?,AI (Artificial Intelligence) is the ability of...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,Input + Rules = Output).,None,None,None,None
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep learning is a,None,None,None,None
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
5,What is training data?,Training data is the data used to teach a Mach...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
7,What is supervised learning?,Supervised learning trains a model using examp...,It is a,None,None,None,None
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning is when,None,None,None,None
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...",ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
11,What is Generative AI?,Generative AI is AI that can create new conten...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
12,What is a prompt?,A prompt is the instruction or input given to ...,"A prompt is the message,",None,None,None,None
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt engineering is the art,None,None,None,None
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,ERROR: 503 UNAVAILABLE. {'error': {'code': 503...,None,None,None,None
16,What is a vector database?,A vector database stores numerical representat...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,None,None,None,None
17,What are embeddings?,Embeddings are numerical representations of te...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,None,None,None,None
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,None,None,None,None
19,How can AI be used in education?,AI can support education by explaining concept...,ERROR: 429 RESOURCE_EXHAUSTED. {'error': {'cod...,None,None,None,None

In [8]:
df

,User Query,Teacher Response,GeneratedAnswer,AnswerCorrectness,AnswerRelevancy,Helpfulness,AnswerQuality
0,What is AI?,AI (Artificial Intelligence) is the ability of...,AI (Artificial Intelligence) is technology tha...,0.890,1.000,1.000,0.963
1,How does AI differ from traditional programming?,Traditional programs follow fixed rules writte...,Traditional programming follows explicit rules...,1.000,1.000,1.000,1.000
2,What is Machine Learning?,Machine Learning is a branch of AI where compu...,Machine Learning is a way for computers to lea...,0.900,1.000,1.000,0.967
3,What is Deep Learning?,Deep Learning is a type of Machine Learning th...,Deep Learning is a type of AI that uses artifi...,0.729,1.000,1.000,0.910
4,"What is the difference between AI, ML, and Dee...",AI is the broad field of making machines intel...,AI is the broad idea of making computers perfo...,0.900,1.000,1.000,0.967
5,What is training data?,Training data is the data used to teach a Mach...,Training data is the information used to teach...,0.900,1.000,1.000,0.967
6,What is a Machine Learning model?,A Machine Learning model is a mathematical sys...,A machine learning model is a computer program...,0.900,1.000,1.000,0.967
7,What is supervised learning?,Supervised learning trains a model using examp...,Supervised learning is a type of machine learn...,0.900,1.000,0.998,0.966
8,What is unsupervised learning?,Unsupervised learning works with data that doe...,Unsupervised learning is a type of machine lea...,0.969,1.000,1.000,0.990
9,What is reinforcement learning?,Reinforcement learning teaches an agent throug...,Reinforcement learning is a type of machine le...,1.000,1.000,0.900,0.967
10,What is an LLM?,"An LLM, or Large Language Model, is an AI mode...",An LLM (Large Language Model) is an AI trained...,0.980,1.000,1.000,0.993
11,What is Generative AI?,Generative AI is AI that can create new conten...,Generative AI is technology that creates new c...,0.900,1.000,1.000,0.967
12,What is a prompt?,A prompt is the instruction or input given to ...,"A prompt is a question, instruction, or messag...",0.900,1.000,1.000,0.967
13,What is Prompt Engineering?,Prompt Engineering is the practice of designin...,Prompt engineering is the skill of writing cle...,0.834,1.000,1.000,0.945
14,What is RAG?,RAG stands for Retrieval-Augmented Generation....,RAG (Retrieval-Augmented Generation) helps AI ...,0.900,1.000,1.000,0.967
15,Why is RAG useful?,RAG is useful when an AI application needs to ...,RAG lets an AI search trusted documents before...,0.700,1.000,0.948,0.883
16,What is a vector database?,A vector database stores numerical representat...,A vector database stores information as number...,0.887,1.000,0.921,0.936
17,What are embeddings?,Embeddings are numerical representations of te...,"Embeddings are numbers that represent words, i...",0.901,1.000,0.967,0.956
18,What is an AI Agent?,An AI Agent is a system that can understand a ...,An AI agent is a computer program that can und...,0.900,0.571,1.000,0.824
19,How can AI be used in education?,AI can support education by explaining concept...,AI can personalize lessons by adapting to each...,0.775,1.000,0.996,0.924

In [15]:
average_result=pd.DataFrame(columns=["average_correctness","average_relevancy","average_helpfulness","average_quality"],
                            data=[[average_correctness,average_relevancy,average_helpfulness,average_quality]])

In [16]:
average_result

,average_correctness,average_relevancy,average_helpfulness,average_quality
0,0.87875,1.0,0.9985,0.9591